[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GradedArrays = "bc96ca6e-b7c8-4bb6-888e-c93f838762c2"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[compat]
Documenter = "1"
GradedArrays = "0.3"
Literate = "2"
